steps:
  # Passo 1: Construir o JAR usando Maven
  - name: 'maven:3.6.3-jdk-8'
    entrypoint: 'mvn'
    args: ['clean', 'package']
    
  # Passo 2: Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/locadora-app', '.']
    
  # Passo 3: Enviar a imagem Docker para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/locadora-app']

images:
  - 'gcr.io/$PROJECT_ID/locadora-app'